Educacion/Education/Education.Web/Controllers/AlumnosController.cs
using Education.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class AlumnosController : Controller
    {
        // GET: Alumnos
        public ActionResult Index()
        {
            var alumnosBL = new AlumnosBL();
            var listadeAlumnos = alumnosBL.ObtenerAlumnos();

            return View(listadeAlumnos);
        }
    }
}

Educacion/Education/Education.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Educacion/Education/Education.Web/Views/Alumnos/Index.cshtml
@model List<Education.BL.Alumno>

@{
    ViewBag.Title = "Index";
}

<h2>Alumnos</h2>

<table class="table table-bordered table-hover">
   <thead>
       <tr>
           <th>
               Codigo
           </th>
           <th>
               NombreAlumno
           </th>
           <th>
               RTN
           </th>
       </tr>
   </thead>
     @foreach (var alumno in Model)
    {
        <tr>
            <td>@alumno.Id</td>
            <td>@alumno.NombreAlumno</td>
            <td>@alumno.RTN</td>
        </tr>
    }
</table>

Educacion/Education/Education.Web/Views/Home/Index.cshtml

@{
    ViewBag.Title = "Index";
}

<h2>Bienvenidos al Sistema de Educacion</h2>


Educacion/Education/Education.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Secundaria", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio","Index","Home")
                    </li>
                    <li>
                        @Html.ActionLink("lista de Alumnos", "Index", "Alumnos")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>